# Learn more about configuring your Customer account UI extension:
# https://shopify.dev/api/customer-account-ui-extensions/unstable/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "unstable"

[[extensions]]
name = "customer-account-ui-3"
handle = "customer-account-ui-3"
type = "ui_extension"


# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/MenuActionExtension.jsx"
target = "customer-account.order-status.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/configuration#network-access
# network_access = true

[extensions.settings]
[[extensions.settings.fields]]
key = "image_url"
type = "single_line_text_field"
name = "Image URL"

[[extensions.settings.fields]]
key = "title"
type = "single_line_text_field"
name = "Title"

[[extensions.settings.fields]]
key = "description"
type = "single_line_text_field"
name = "Description"

[[extensions.settings.fields]]
key = "btn_text"
type = "single_line_text_field"
name = "Button Text"

[[extensions.settings.fields]]
key = "btn_type"
type = "single_line_text_field"
name = "Button appearance"
  [[extensions.settings.fields.validations]]
  name="choices"
  value="[\"critical\",\"warning\",\"monochrome\"]"
